### ISSUE TITLE
Action to add checklist to PR body

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter-reviews#37]
## Problem

We have to step through the same review steps on every PR which is hard to always remember. Plus, it's not as transparent to the public where a review is unless we comment as we review it.

## Proposal

Have an action to automatically throw a checklist into the PR body so we can check those off as it's reviewed.

## Prior Art

I've seen actions that comment on a PR with a checklist, but using the PR body is nice because GitHub considers it the overall progress for the PR in the header and on the PRs page.

**Comment by cassidyjames** [comment]
Example list:

- [x] App opens
- [x] Does what it says
- [x] Matches description in AppData
- [x] Matches screenshot
- [x] AppData custom colors are contrasty
- [x] Name is unique and non-confusing

There's probably more to check, but this is a start.
